"""roles table

Revision ID: 136e47f7dc02
Revises: d5988102714a
Create Date: 2019-02-28 10:59:39.868941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136e47f7dc02'
down_revision = 'd5988102714a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=1500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_description'), 'role', ['description'], unique=True)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_description'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
