"""topics table

Revision ID: 3b88b0965236
Revises: 753cef572e7d
Create Date: 2019-03-13 16:50:20.516726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b88b0965236'
down_revision = '753cef572e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_description'), 'topic', ['description'], unique=True)
    op.create_index(op.f('ix_topic_name'), 'topic', ['name'], unique=True)
    op.create_index(op.f('ix_topic_text'), 'topic', ['text'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_text'), table_name='topic')
    op.drop_index(op.f('ix_topic_name'), table_name='topic')
    op.drop_index(op.f('ix_topic_description'), table_name='topic')
    op.drop_table('topic')
    # ### end Alembic commands ###
