"""lesson table

Revision ID: a52726cf41c3
Revises: 3b88b0965236
Create Date: 2019-03-28 23:30:30.061523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52726cf41c3'
down_revision = '3b88b0965236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_description'), 'lesson', ['description'], unique=True)
    op.create_index(op.f('ix_lesson_name'), 'lesson', ['name'], unique=True)
    op.create_index(op.f('ix_lesson_text'), 'lesson', ['text'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_text'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_name'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_description'), table_name='lesson')
    op.drop_table('lesson')
    # ### end Alembic commands ###
