"""roles table

Revision ID: ab28ec62821f
Revises: 142c0460f52e
Create Date: 2019-02-27 20:44:04.521010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab28ec62821f'
down_revision = '142c0460f52e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=1500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_description'), 'role', ['description'], unique=True)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_description'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
