"""lessons table

Revision ID: d61ee13bf7c5
Revises: 3b88b0965236
Create Date: 2019-03-27 16:41:09.067056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61ee13bf7c5'
down_revision = '3b88b0965236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_description'), 'lesson', ['description'], unique=True)
    op.create_index(op.f('ix_lesson_name'), 'lesson', ['name'], unique=True)
    op.create_index(op.f('ix_lesson_text'), 'lesson', ['text'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_text'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_name'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_description'), table_name='lesson')
    op.drop_table('lesson')
    # ### end Alembic commands ###
